# Generated by Django 5.2.8 on 2025-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Photo', models.ImageField(upload_to='Images/school_app_files/student_photos/')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_Number', models.CharField(max_length=10)),
                ('Class', models.PositiveIntegerField()),
                ('Section', models.CharField(max_length=1)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Student_Mobile_Number', models.PositiveIntegerField(unique=True)),
                ('Parent_Name', models.CharField(max_length=50)),
                ('ParentContact_Number', models.PositiveIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('fee', models.FloatField(default=30000)),
                ('Admission_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Photo', models.ImageField(upload_to='Images/school_app_files/teachers_photos/')),
                ('Employee_ID', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Experience_Years', models.FloatField(max_length=50)),
                ('Joining_Date', models.DateField(auto_now_add=True)),
                ('Salary', models.FloatField(default=40000)),
                ('Contact_Number', models.PositiveIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
