# Generated by Django 5.2.9 on 2025-12-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_Number', models.CharField(max_length=10, unique=True)),
                ('Class', models.PositiveIntegerField()),
                ('Section', models.CharField(max_length=1)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Student_ph_No', models.PositiveBigIntegerField(unique=True)),
                ('fee', models.FloatField(default=30000)),
                ('Admission_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.CharField(max_length=50, unique=True)),
                ('Full_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Qualification', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=50)),
                ('Experience_Years', models.FloatField()),
                ('Joining_Date', models.DateField(auto_now_add=True)),
                ('Salary', models.FloatField(default=40000)),
                ('Contact_Number', models.PositiveBigIntegerField(unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
