# Generated by Django 5.2.8 on 2025-11-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='ParentContact_Number',
            new_name='Parent_ph_No',
        ),
        migrations.RenameField(
            model_name='student_details',
            old_name='Student_Mobile_Number',
            new_name='Student_ph_No',
        ),
    ]
