# Generated by Django 5.2.8 on 2025-11-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_parentcontact_number_student_details_parent_ph_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='Parent_Name',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='Parent_ph_No',
        ),
        migrations.RemoveField(
            model_name='teachers_details',
            name='Address',
        ),
    ]
