# Generated by Django 5.2.8 on 2025-11-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_remove_student_details_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='Profile_Photo',
        ),
        migrations.RemoveField(
            model_name='teachers_details',
            name='Profile_Photo',
        ),
    ]
