# Generated by Django 5.2.8 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_remove_student_details_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Date_of_Birth',
            field=models.DateField(),
        ),
    ]
