# Generated by Django 5.2.8 on 2025-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_student_details_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_details',
            name='Experience_Years',
            field=models.FloatField(),
        ),
    ]
