# Generated by Django 5.2.8 on 2025-11-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_teachers_details_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Roll_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers_details',
            name='Employee_ID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
