# Generated by Django 5.2.8 on 2025-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_student_details_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Student_ph_No',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teachers_details',
            name='Contact_Number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
